#!/bin/sh

# The SPI-HUB Spartan6 FPGA image maps the C3FPGA_GPIO0 line to
# PROGB of the primary FPGA of the first attached ZMP003-FPGA1 board.

# On the iMX processor, C3FPGA_GPIO0 is on pin EIM_A16, which is
# internally muxed to the GPIO2_IO22 signal.

# From the Linux kernel's perspective GPIO2_IO22 => (2-1)*32 + 22 = 54

# A similar arrangement is present for the second attached ZMP003-FPGA
# board, but with C3FPGA_GPIO2, EIM_A18, GPIO2_IO20.

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: $0 [<boardnum>]"
    echo "  where boardnum is '1' or '2', defaulting to '1' if not present."
    exit 0
elif [ "$1" = "" ] || [ "$1" = "1" ]; then
    # first board
    GPIO=54
elif [ "$1" = "2" ]; then
    # second board
    GPIO=52
else
    echo "Unknown board number: $1.  Use '1' or '2' only."
    exit 1
fi

# Setup GPIO to control the FPGA PROGB line
if ! [ -e /sys/class/gpio/gpio${GPIO} ]; then
    echo ${GPIO} >/sys/class/gpio/export
fi
echo out >/sys/class/gpio/gpio${GPIO}/direction

# Hold PROGB low to disable FPGA
echo 0 >/sys/class/gpio/gpio${GPIO}/value

# Pause for 1 second
sleep 1

# Raise PROGB high to allow FPGA to reconfigure
echo 1 >/sys/class/gpio/gpio${GPIO}/value
